from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('jewellery/', views.catalogue, name='catalogue'),
    path('collection/<slug:slug>/', views.collection_detail, name='collection'),
    path('jewellery/<slug:slug>/', views.product_detail, name='product_detail'),
    path('bag/', views.cart_view, name='cart'),
    path('bag/add/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('bag/update/<int:pk>/', views.update_cart, name='update_cart'),
    path('bag/remove/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('checkout/success/', views.checkout_success, name='checkout_success'),
    path('account/signup/', views.signup, name='signup'),
    path('account/activate/<uidb64>/<token>/', views.activate_account, name='activate_account'),
    path('account/privacy/erase/', views.request_privacy_erasure, name='request_privacy_erasure'),
    path('feedback/', views.submit_review, name='feedback'),
    path('review/', views.submit_review, name='submit_review'),
    path('analytics/click/', views.analytics_click, name='analytics_click'),
    path('controlpanel/', views.control_panel, name='control_panel'),
    path('controlpanel/analytics/', views.control_analytics, name='control_analytics'),
    path('controlpanel/reviews/', views.control_reviews, name='control_reviews'),
    path('controlpanel/products/', views.control_products, name='control_products'),
    path('controlpanel/stock/', views.control_stock, name='control_stock'),
    path('controlpanel/collections/', views.control_collections, name='control_collections'),
    path('controlpanel/delivery/', views.control_delivery, name='control_delivery'),
    path('controlpanel/orders/', views.control_orders, name='control_orders'),
    path('controlpanel/orders/<int:pk>/pdf/', views.control_order_pdf, name='control_order_pdf'),
    path('controlpanel/sales/', views.control_sales, name='control_sales'),
    path('controlpanel/users/', views.control_users, name='control_users'),
    path('payments/stripe/webhook/', views.stripe_webhook, name='stripe_webhook'),
    path('contact/', views.enquiry, name='contact'),
    path('account/', views.account, name='account'),
]
