from django.urls import path
from . import dashboard, views
from . import sales_charts
from . import analytics_charts
from . import user_dashboard

urlpatterns = [
    path('', views.home, name='home'),
    path('heritage/', views.heritage, name='heritage'),
    path('custom-design/', views.custom_design, name='custom_design'),
    path('custom-design/<int:pk>/photo/', views.custom_design_photo, name='custom_design_photo'),
    path('assistant/message/', views.store_assistant, name='store_assistant'),
    path('jewellery/', views.catalogue, name='catalogue'),
    path('collection/<slug:slug>/', views.collection_detail, name='collection'),
    path('jewellery/<slug:slug>/', views.product_detail, name='product_detail'),
    path('jewellery/<slug:slug>/pre-order/', views.preorder_interest_product, name='preorder_interest_product'),
    path('jewellery/<slug:slug>/stock-notification/', views.restock_notification, name='restock_notification'),
    path('jewellery/<slug:slug>/add-to-bag/', views.restock_add_to_bag, name='restock_add_to_bag'),
    path('bag/', views.cart_view, name='cart'),
    path('bag/add/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('bag/update/<int:pk>/', views.update_cart, name='update_cart'),
    path('bag/remove/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('checkout/success/', views.checkout_success, name='checkout_success'),
    path('account/signup/', views.signup, name='signup'),
    path('account/activate/<uidb64>/<token>/', views.activate_account, name='activate_account'),
    path('account/privacy/erase/', views.request_privacy_erasure, name='request_privacy_erasure'),
    path('feedback/', views.submit_review, name='feedback'),
    path('review/', views.submit_review, name='submit_review'),
    path('analytics/click/', views.analytics_click, name='analytics_click'),
    path('controlpanel/', views.control_panel, name='control_panel'),
    path('controlpanel/charts/inventory/', dashboard.InventoryChartView.as_view(), name='dashboard_inventory_chart'),
    path('controlpanel/charts/fulfilment/', dashboard.FulfilmentChartView.as_view(), name='dashboard_fulfilment_chart'),
    path('controlpanel/charts/team/', dashboard.TeamWorkloadChartView.as_view(), name='dashboard_team_chart'),
    path('controlpanel/analytics/', views.control_analytics, name='control_analytics'),
    path('controlpanel/analytics/charts/mix/', analytics_charts.ActivityMixChartView.as_view(), name='analytics_mix_chart'),
    path('controlpanel/analytics/charts/locations/', analytics_charts.ConnectionsLocationChartView.as_view(), name='analytics_locations_chart'),
    path('controlpanel/analytics/charts/timeline/', analytics_charts.ActivityTimelineChartView.as_view(), name='analytics_timeline_chart'),
    path('controlpanel/analytics/charts/pages/', analytics_charts.TopPagesChartView.as_view(), name='analytics_pages_chart'),
    path('controlpanel/analytics/charts/products/', analytics_charts.ProductActivityChartView.as_view(), name='analytics_products_chart'),
    path('controlpanel/reviews/', views.control_reviews, name='control_reviews'),
    path('controlpanel/custom-requests/', views.control_custom_requests, name='control_custom_requests'),
    path('controlpanel/products/', views.control_products, name='control_products'),
    path('controlpanel/stock/', views.control_stock, name='control_stock'),
    path('controlpanel/stock/history/', views.control_stock_history, name='control_stock_history'),
    path('controlpanel/collections/', views.control_collections, name='control_collections'),
    path('controlpanel/delivery/', views.control_delivery, name='control_delivery'),
    path('controlpanel/orders/', views.control_orders, name='control_orders'),
    path('controlpanel/orders/<int:pk>/pdf/', views.control_order_pdf, name='control_order_pdf'),
    path('controlpanel/sales/', views.control_sales, name='control_sales'),
    path('controlpanel/sales/completed/', views.control_sales_details, {'section': 'completed'}, name='control_sales_completed'),
    path('controlpanel/sales/reconciliation/', views.control_sales_details, {'section': 'reconciliation'}, name='control_sales_reconciliation'),
    path('controlpanel/sales/replenishment/', views.control_sales_details, {'section': 'replenishment'}, name='control_sales_replenishment'),
    path('controlpanel/sales/charts/revenue/', sales_charts.SalesRevenueChartView.as_view(), name='sales_revenue_chart'),
    path('controlpanel/sales/charts/receipts/', sales_charts.SalesReceiptsChartView.as_view(), name='sales_receipts_chart'),
    path('controlpanel/sales/charts/replenishment/', sales_charts.ReplenishmentCostChartView.as_view(), name='sales_replenishment_chart'),
    path('controlpanel/users/', views.control_users, name='control_users'),
    path('controlpanel/users/charts/roles/', user_dashboard.UserRoleChartView.as_view(), name='users_role_chart'),
    path('controlpanel/users/charts/engagement/', user_dashboard.UserEngagementChartView.as_view(), name='users_engagement_chart'),
    path('payments/stripe/webhook/', views.stripe_webhook, name='stripe_webhook'),
    path('contact/', views.enquiry, name='contact'),
    path('account/', views.account, name='account'),
]
