from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth','0012_alter_user_first_name_max_length')]
    operations = [
        migrations.CreateModel(name='Collection', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('slug',models.SlugField(unique=True)),('description',models.TextField(blank=True)),('image',models.ImageField(blank=True,null=True,upload_to='collections/')),('active',models.BooleanField(default=True))]),
        migrations.CreateModel(name='Product', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=200)),('slug',models.SlugField(unique=True)),('sku',models.CharField(max_length=60,unique=True)),('description',models.TextField()),('short_description',models.CharField(blank=True,max_length=300)),('price',models.DecimalField(decimal_places=2,max_digits=10)),('compare_at_price',models.DecimalField(blank=True,decimal_places=2,max_digits=10,null=True)),('material',models.CharField(blank=True,max_length=120)),('dimensions',models.CharField(blank=True,max_length=200)),('stock_quantity',models.PositiveIntegerField(default=0)),('featured',models.BooleanField(default=False)),('active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('collection',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='products',to='shop.collection'))]),
        migrations.CreateModel(name='ProductImage', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('image',models.ImageField(upload_to='products/')),('alt_text',models.CharField(blank=True,max_length=200)),('is_primary',models.BooleanField(default=False)),('sort_order',models.PositiveIntegerField(default=0)),('product',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='images',to='shop.product'))]),
        migrations.CreateModel(name='Enquiry', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('email',models.EmailField(max_length=254)),('phone',models.CharField(blank=True,max_length=50)),('subject',models.CharField(blank=True,max_length=200)),('message',models.TextField()),('created_at',models.DateTimeField(auto_now_add=True)),('handled',models.BooleanField(default=False))]),
        migrations.CreateModel(name='Order', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('email',models.EmailField(max_length=254)),('status',models.CharField(choices=[('pending','Pending'),('paid','Paid'),('processing','Processing'),('shipped','Shipped'),('completed','Completed'),('cancelled','Cancelled')],default='pending',max_length=20)),('stripe_session_id',models.CharField(blank=True,max_length=255,null=True,unique=True)),('shipping_name',models.CharField(max_length=160)),('shipping_address1',models.CharField(max_length=255)),('shipping_address2',models.CharField(blank=True,max_length=255)),('shipping_city',models.CharField(max_length=100)),('shipping_postcode',models.CharField(max_length=30)),('shipping_country',models.CharField(default='United Kingdom',max_length=80)),('subtotal',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('shipping',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('total',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='orders',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='OrderItem', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('product_name',models.CharField(max_length=200)),('sku',models.CharField(max_length=60)),('unit_price',models.DecimalField(decimal_places=2,max_digits=10)),('quantity',models.PositiveIntegerField()),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='shop.order')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='shop.product'))]),
    ]
