# Generated by Django 5.2.17 on 2026-09-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_privacyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='house_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='street_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
