# Generated by Django 5.2.17 on 2026-09-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_customerprofile_city_customerprofile_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('', 'Select a title'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Mx', 'Mx'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=10),
        ),
    ]
