# Generated by Django 5.2.17 on 2026-09-23 00:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_billing_address1_order_billing_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('standard_uk', 'UK Standard delivery'), ('express_uk', 'UK Express delivery'), ('international', 'International delivery')], default='standard_uk', max_length=30),
        ),
    ]
