# Generated by Django 5.2.17 on 2026-09-23 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_customerreview_analyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='shop.product'),
        ),
    ]
