# Generated by Django 5.2.17 on 2026-09-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_analyticsevent_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_reference',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True),
        ),
    ]
