# Generated by Django 5.2.17 on 2026-09-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_ipgeolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
