# Generated by Django 5.2.17 on 2026-09-23 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_enquiry_responded_at_enquiry_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='response',
        ),
        migrations.CreateModel(
            name='EnquiryReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='shop.enquiry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
