# Generated by Django 5.2.17 on 2026-09-23 17:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_enquiry_responded_at_remove_enquiry_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Product cost price at time of order, snapshotted for accurate historical margin reporting.', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Unit cost to source/manufacture this piece, used for margin and replenishment budgeting.', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=5, help_text='Reorder when stock falls to or below this quantity.'),
        ),
        migrations.AddField(
            model_name='product',
            name='restock_target',
            field=models.PositiveIntegerField(default=20, help_text='Target stock quantity to replenish up to.'),
        ),
    ]
