# Generated by Django 5.2.17 on 2026-09-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_order_payment_confirmation_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('return', 'Return'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
