# Generated by Django 5.2.17 on 2026-09-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_update_standard_shipping_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('blocked_at', models.DateTimeField(auto_now=True)),
                ('blocked_until', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('event_type', models.CharField(choices=[('auto_block', 'Automatic IP block'), ('unblocked', 'IP unblocked')], max_length=20)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('reason', models.CharField(max_length=255)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='shop_securi_created_dffdb7_idx')],
            },
        ),
    ]
