# Generated by Django 5.2.17 on 2026-10-04 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def record_opening_balances(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    StockMovement = apps.get_model('shop', 'StockMovement')
    database = schema_editor.connection.alias
    StockMovement.objects.using(database).bulk_create([
        StockMovement(product=product, product_name=product.name, sku=product.sku, reason='opening', quantity_change=0, balance_before=product.stock_quantity, balance_after=product.stock_quantity)
        for product in Product.objects.using(database).all().iterator()
    ], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_order_stock_deducted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=60)),
                ('reason', models.CharField(choices=[('opening', 'Opening balance'), ('restock', 'Restock'), ('adjustment', 'Manual adjustment'), ('sale', 'Paid purchase')], max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('balance_before', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('actor_name', models.CharField(blank=True, max_length=310)),
                ('order_reference', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='shop.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='shop.product')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='shop_stock_product_date_idx')],
            },
        ),
        migrations.RunPython(record_opening_balances, migrations.RunPython.noop),
    ]
