# Generated by Django 5.2.17 on 2026-10-04 00:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_stock_movement_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manual_entry_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_channel',
            field=models.CharField(choices=[('stripe', 'Stripe / card'), ('cash', 'Cash'), ('gift', 'Free gift'), ('gift_card', 'Gift card')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('restock', 'Restock'), ('adjustment', 'Manual adjustment'), ('sale', 'Paid purchase'), ('gift', 'Free gift')], max_length=20),
        ),
        migrations.CreateModel(
            name='StripeSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('currency', models.CharField(max_length=3)),
                ('livemode', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=20)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='StripeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255, unique=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('livemode', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_transactions', to='shop.order')),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
    ]
