# Generated by Django 5.2.17 on 2026-10-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_sales_channels_stripe_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_notes',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='stripetransaction',
            name='refund_notes',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
